baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Brahim Hamdouni Documentation"
theme = "learn"
#themesdir = "../.."
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/hamdouni/documentation/edit/master/content/"
  description = "Documentation for Brahim Hamdouni"
  author = "Brahim Hamdouni"
  showVisitedLinks = true
  disableBreadcrumb = true
  disableNextPrev = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for Brahim Hamdouni"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/hamdouni/documentation"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Showcases"
url = "showcase"
weight = 11

[Languages.fr]
title = "Documentation de Brahim Hamdouni"
weight = 2
languageName = "Français"

[[Languages.fr.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Repo Github"
identifier = "ds"
url = "https://github.com/hamdouni/documentation"
weight = 10

